sudo: required
services:
  - docker

before_install:
  - docker build -t jackdough/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jackdough/docker-react npm run test -- --coverage